import type { Asset } from './types';

// Seed data — 18 assets across 4 types, varied tags, uploaders, dates.
// Two are in the trash so the 回收站 view is non-empty on first load.

export const MOCK_ASSETS: Asset[] = [
  // ── Images (8) ────────────────────────────────────────────────────────
  {
    id: 'a01',
    orgId: 'org-mock',
    name: 'hero-banner.png',
    type: 'image',
    format: 'PNG',
    size: 2_400_000,
    uploadedAt: '2026-06-01T09:12:00Z',
    uploadedBy: '张三',
    tags: ['品牌物料', '首页', '2026'],
    favorite: true,
    deletedAt: null,
    width: 1920,
    height: 600,
  },
  {
    id: 'a02',
    orgId: 'org-mock',
    name: 'product-01.jpg',
    type: 'image',
    format: 'JPG',
    size: 840_000,
    uploadedAt: '2026-05-28T14:33:00Z',
    uploadedBy: '李四',
    tags: ['产品图', '首页'],
    favorite: false,
    deletedAt: null,
    width: 800,
    height: 800,
  },
  {
    id: 'a03',
    orgId: 'org-mock',
    name: 'logo-color.svg',
    type: 'image',
    format: 'SVG',
    size: 12_000,
    uploadedAt: '2026-04-15T10:01:00Z',
    uploadedBy: '张三',
    tags: ['品牌物料'],
    favorite: true,
    deletedAt: null,
  },
  {
    id: 'a04',
    orgId: 'org-mock',
    name: 'bg-texture.png',
    type: 'image',
    format: 'PNG',
    size: 1_100_000,
    uploadedAt: '2026-03-22T16:48:00Z',
    uploadedBy: '王五',
    tags: ['品牌物料', '营销素材'],
    favorite: false,
    deletedAt: null,
    width: 2560,
    height: 1440,
  },
  {
    id: 'a05',
    orgId: 'org-mock',
    name: 'team-photo.jpg',
    type: 'image',
    format: 'JPG',
    size: 1_650_000,
    uploadedAt: '2026-05-10T11:20:00Z',
    uploadedBy: '李四',
    tags: ['品牌物料', '团队'],
    favorite: false,
    deletedAt: null,
    width: 1600,
    height: 1067,
  },
  {
    id: 'a06',
    orgId: 'org-mock',
    name: 'icon-set.zip',
    type: 'document',
    format: 'ZIP',
    size: 320_000,
    uploadedAt: '2026-05-05T09:00:00Z',
    uploadedBy: '王五',
    tags: ['品牌物料', '设计资源'],
    favorite: false,
    deletedAt: null,
  },
  {
    id: 'a07',
    orgId: 'org-mock',
    name: 'social-cover.png',
    type: 'image',
    format: 'PNG',
    size: 480_000,
    uploadedAt: '2026-06-02T08:30:00Z',
    uploadedBy: '张三',
    tags: ['营销素材', '社交'],
    favorite: true,
    deletedAt: null,
    width: 1200,
    height: 630,
  },
  {
    id: 'a08',
    orgId: 'org-mock',
    name: 'old-logo.png',
    type: 'image',
    format: 'PNG',
    size: 60_000,
    uploadedAt: '2026-01-10T12:00:00Z',
    uploadedBy: '张三',
    tags: ['品牌物料', '历史'],
    favorite: false,
    deletedAt: '2026-05-20T09:00:00Z', // in trash
    width: 512,
    height: 512,
  },

  // ── Videos (3) ────────────────────────────────────────────────────────
  {
    id: 'v01',
    orgId: 'org-mock',
    name: 'intro-reel.mp4',
    type: 'video',
    format: 'MP4',
    size: 48_000_000,
    uploadedAt: '2026-05-18T15:00:00Z',
    uploadedBy: '李四',
    tags: ['营销素材', '首页'],
    favorite: true,
    deletedAt: null,
    width: 1920,
    height: 1080,
    duration: 32,
  },
  {
    id: 'v02',
    orgId: 'org-mock',
    name: 'demo-loop.webm',
    type: 'video',
    format: 'WEBM',
    size: 6_200_000,
    uploadedAt: '2026-05-25T10:45:00Z',
    uploadedBy: '王五',
    tags: ['产品图', '营销素材'],
    favorite: false,
    deletedAt: null,
    width: 1280,
    height: 720,
    duration: 8,
  },
  {
    id: 'v03',
    orgId: 'org-mock',
    name: 'testimonial-zhang.mp4',
    type: 'video',
    format: 'MP4',
    size: 22_500_000,
    uploadedAt: '2026-04-30T14:00:00Z',
    uploadedBy: '张三',
    tags: ['营销素材', '客户故事'],
    favorite: false,
    deletedAt: null,
    width: 1920,
    height: 1080,
    duration: 48,
  },

  // ── Documents (4) ─────────────────────────────────────────────────────
  {
    id: 'd01',
    orgId: 'org-mock',
    name: 'brand-guidelines.pdf',
    type: 'document',
    format: 'PDF',
    size: 5_400_000,
    uploadedAt: '2026-02-12T09:30:00Z',
    uploadedBy: '张三',
    tags: ['品牌物料', '规范'],
    favorite: true,
    deletedAt: null,
  },
  {
    id: 'd02',
    orgId: 'org-mock',
    name: 'q2-roadmap.docx',
    type: 'document',
    format: 'DOCX',
    size: 240_000,
    uploadedAt: '2026-05-30T11:15:00Z',
    uploadedBy: '王五',
    tags: ['内部', '规划'],
    favorite: false,
    deletedAt: null,
  },
  {
    id: 'd03',
    orgId: 'org-mock',
    name: 'launch-plan.pdf',
    type: 'document',
    format: 'PDF',
    size: 1_800_000,
    uploadedAt: '2026-04-22T13:20:00Z',
    uploadedBy: '李四',
    tags: ['内部', '营销素材', '规划'],
    favorite: false,
    deletedAt: null,
  },
  {
    id: 'd04',
    orgId: 'org-mock',
    name: 'old-deck.pptx',
    type: 'document',
    format: 'PPTX',
    size: 3_200_000,
    uploadedAt: '2026-01-15T10:00:00Z',
    uploadedBy: '王五',
    tags: ['历史'],
    favorite: false,
    deletedAt: '2026-05-22T16:00:00Z', // in trash
  },

  // ── Audio (3) ─────────────────────────────────────────────────────────
  {
    id: 'au01',
    orgId: 'org-mock',
    name: 'podcast-ep12.mp3',
    type: 'audio',
    format: 'MP3',
    size: 38_000_000,
    uploadedAt: '2026-06-03T07:00:00Z',
    uploadedBy: '李四',
    tags: ['营销素材', '播客'],
    favorite: false,
    deletedAt: null,
    duration: 2640, // 44:00
  },
  {
    id: 'au02',
    orgId: 'org-mock',
    name: 'jingle-short.wav',
    type: 'audio',
    format: 'WAV',
    size: 4_200_000,
    uploadedAt: '2026-05-12T15:30:00Z',
    uploadedBy: '张三',
    tags: ['品牌物料', '营销素材'],
    favorite: true,
    deletedAt: null,
    duration: 15,
  },
  {
    id: 'au03',
    orgId: 'org-mock',
    name: 'soundtrack.mp3',
    type: 'audio',
    format: 'MP3',
    size: 8_900_000,
    uploadedAt: '2026-04-08T19:00:00Z',
    uploadedBy: '王五',
    tags: ['产品图', '营销素材'],
    favorite: false,
    deletedAt: null,
    duration: 372, // 6:12
  },
];
